development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
<<<<<<< HEAD
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: test_app_production
=======
  url: redis://localhost:6379/1
>>>>>>> origin/master
